// SPDX-License-Identifier: LGPL-3.0-only
// SPDX-FileCopyrightText: 2024-2026 Nicholas Amorim <nicholas@santos.ee>

import Foundation

/// The eight Viznut-style bytebeat formulas, ported one-for-one from
/// `main/bytebeat_songs.inc` in the Phonicbloom BSAFE firmware.
///
/// Each song reads:
/// - `songPtr` — the ever-incrementing counter. `Int32` here to match the
///   truncation width of the ESP32's native `int`.
/// - `bit1`, `bit2` — bit-rate dividers.
/// - `varP` — four modulation variables in `0…255`.
///
/// Each song writes two `UInt8` sample values (`left`, `right`), one per
/// channel. The device casts these to `float`, then reads them as unsigned
/// 16-bit before shifting by `BB_SHIFT_VOLUME` for the DAC.
///
/// ## Overflow semantics
///
/// **Critical:** bytebeat sounds the way it does because signed integer
/// overflow wraps around. All arithmetic uses Swift's overflow operators
/// (`&+`, `&-`, `&*`, `&<<`, `&>>`) and `truncatingIfNeeded:` conversions,
/// so the math matches the C reference exactly. The unit tests compare
/// sample-for-sample against WAVs generated by the original C source.
///
/// The C code uses `int` (32-bit signed on the ESP32-S3 / typical clang
/// targets) for all `tt[i]` arithmetic. We stay in `Int32` throughout each
/// song formula and only truncate at the final store into the `UInt8`.
///
/// > Realtime: safe. Every entry point is `@inlinable`, allocation-free,
/// > lock-free, and branch-lean.
public enum BytebeatSongs {

    /// Number of built-in songs.
    public static let count: Int = 8

    /// Compute one stereo sample for a given song.
    ///
    /// - Parameters:
    ///   - song: Song number in `0…7`. Values outside the range emit silence.
    ///   - songPtr: The current bytebeat counter value, already incremented
    ///     for this sample.
    ///   - bit1: First bit-rate divider. Clamped to `≥ 1`.
    ///   - bit2: Second bit-rate divider. Clamped to `≥ 1`.
    ///   - varP: Four modulation values in `0…255`.
    /// - Returns: A `(left, right)` pair of unsigned 8-bit samples matching
    ///   the `s[0]` / `s[1]` writes in `bytebeat_songs.inc`.
    ///
    /// > Realtime: safe.
    @inlinable
    public static func render(
        song: Int,
        songPtr: Int32,
        bit1: UInt8,
        bit2: UInt8,
        varP: (UInt8, UInt8, UInt8, UInt8)
    ) -> (UInt8, UInt8) {
        // Guard against divide-by-zero. The firmware trusts bit1/bit2 to be
        // ≥ 2, but the UI accepts wider ranges so we clamp here for safety.
        let b1 = Int32(max(1, bit1))
        let b2 = Int32(max(1, bit2))
        let t0 = songPtr / b1
        let t1 = t0 / b2

        let p0 = Int32(varP.0)
        let p1 = Int32(varP.1)
        let p2 = Int32(varP.2)
        let p3 = Int32(varP.3)

        switch song {
        case 0:  return song0(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 1:  return song1(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 2:  return song2(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 3:  return song3(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 4:  return song4(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 5:  return song5(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 6:  return song6(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        case 7:  return song7(t0: t0, t1: t1, p0: p0, p1: p1, p2: p2, p3: p3)
        default: return (0, 0)
        }
    }

    // MARK: - Song formulas
    //
    // Each function reproduces one branch of the `if(bytebeat_song==N)`
    // ladder in `bytebeat_songs.inc`. Line numbers in comments refer to that
    // file. Signed overflow (`&+`, `&*`, `&<<`) matches C `int` behavior; the
    // final truncation to UInt8 matches the C cast to `unsigned char`.

    /// Song 0 (`bytebeat_songs.inc:28`).
    /// `s = t * (t>>11 & t>>(8-p0/5) & (123-p2) & t>>(3+p3/10)) * (p1+1)`
    @inlinable
    static func song0(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32) -> Int32 {
            let sh1 = Int32(11)
            let sh2 = 8 &- p0 / 5
            let sh3 = 3 &+ p3 / 10
            let inner = (t &>> sh1) & (t &>> sh2) & (123 &- p2) & (t &>> sh3)
            return t &* inner &* (p1 &+ 1)
        }
        return (UInt8(truncatingIfNeeded: f(t0)),
                UInt8(truncatingIfNeeded: f(t1)))
    }

    /// Song 1 (`bytebeat_songs.inc:40`).
    /// `s = (t * (t>>(5-p0/20) | t>>(8-p1/20))) >> (t>>(16-p3/10))`
    @inlinable
    static func song1(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32) -> Int32 {
            let a = 5 &- p0 / 20
            let b = 8 &- p1 / 20
            let c = 16 &- p3 / 10
            let mul = t &* ((t &>> a) | (t &>> b))
            return mul &>> (t &>> c)
        }
        return (UInt8(truncatingIfNeeded: f(t0)),
                UInt8(truncatingIfNeeded: f(t1)))
    }

    /// Song 2 (`bytebeat_songs.inc:62`).
    /// `s = t * ((t>>(12-p0/10) | t>>(8±p1/2)) & (63-p2) & t>>(4+p3/8))`
    ///
    /// The C source uses `(8 - p1/2)` for the left channel and `(8 + p1/2)`
    /// for the right, producing stereo width. That asymmetry is preserved.
    @inlinable
    static func song2(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32, _ p1Term: Int32) -> Int32 {
            let a = 12 &- p0 / 10
            let c = 4 &+ p3 / 8
            let inner = ((t &>> a) | (t &>> p1Term)) & (63 &- p2) & (t &>> c)
            return t &* inner
        }
        let l = f(t0, 8 &- p1 / 2)
        let r = f(t1, 8 &+ p1 / 2)
        return (UInt8(truncatingIfNeeded: l),
                UInt8(truncatingIfNeeded: r))
    }

    /// Song 3 (`bytebeat_songs.inc:83`).
    /// `s = t * ((t>>(9-p0/10) | t>>(13-p1/8)) & (25-p3/4) & t>>(6-p2/20))`
    @inlinable
    static func song3(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32) -> Int32 {
            let a = 9 &- p0 / 10
            let b = 13 &- p1 / 8
            let c = 6 &- p2 / 20
            let inner = ((t &>> a) | (t &>> b)) & (25 &- p3 / 4) & (t &>> c)
            return t &* inner
        }
        return (UInt8(truncatingIfNeeded: f(t0)),
                UInt8(truncatingIfNeeded: f(t1)))
    }

    /// Song 4 (`bytebeat_songs.inc:94`).
    /// `s = ((-t & 4095) * (255 & t*(t & t>>(13-p0/10))) >> (12-p1/10))`
    /// `  + (127 & t*(234 & t>>8 & t>>(3+p2/10)) >> (3 & t>>(14-p3/10)))`
    ///
    /// Precedence traps (C: `*` > `>>` > `&`):
    /// - Part A: `(negT * mul1) >> b` — multiplication before shift.
    /// - Part B: `127 & ((t*mul2) >> shift)` — shift binds tighter than `&`.
    @inlinable
    static func song4(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32) -> Int32 {
            let a = 13 &- p0 / 10
            let b = 12 &- p1 / 10
            let c = 3 &+ p2 / 10
            let d = 14 &- p3 / 10

            let negT = (0 &- t) & 4095
            let mul1 = 255 & (t &* (t & (t &>> a)))
            let leftPart = (negT &* mul1) &>> b

            let mul2 = 234 & (t &>> 8) & (t &>> c)
            let rightPart = 127 & ((t &* mul2) &>> (3 & (t &>> d)))

            return leftPart &+ rightPart
        }
        return (UInt8(truncatingIfNeeded: f(t0)),
                UInt8(truncatingIfNeeded: f(t1)))
    }

    /// Song 5 (`bytebeat_songs.inc:115`).
    /// `s = (t * ((t>>((t>>(9-p1/10))|(t>>8))) & (63-p2/2) & (t>>(4+p3/10))))`
    /// `  + ((t^(t>>8)) | (((t<<3) & (56-p0/2)) ^ t))`
    ///
    /// Precedence trap: the outer `t * (...)` wraps the entire AND-chain, so
    /// we precompute `inner` before multiplying by `t` — otherwise Swift's
    /// `MultiplicationPrecedence` would fold `t*shift` with the first `&`.
    @inlinable
    static func song5(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32) -> Int32 {
            let a = 9 &- p1 / 10
            let d = 4 &+ p3 / 10

            let innerShift = (t &>> a) | (t &>> 8)
            let inner = (t &>> innerShift) & (63 &- p2 / 2) & (t &>> d)
            let firstMul = t &* inner

            let xored = t ^ (t &>> 8)
            let second = xored | (((t &<< 3) & (56 &- p0 / 2)) ^ t)

            return firstMul &+ second
        }
        return (UInt8(truncatingIfNeeded: f(t0)),
                UInt8(truncatingIfNeeded: f(t1)))
    }

    /// Song 6 (`bytebeat_songs.inc:208`).
    /// `s = (p0+1) * t * t * ~((t>>16 | t>>12) / (p2+1) & 215 & ~t>>(8±p1/2)) / (p3+1)`
    ///
    /// Left uses `(8 + p1/2)`, right uses `(8 - p1/2)` — preserved for stereo.
    @inlinable
    static func song6(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32, _ p1Shift: Int32) -> Int32 {
            let orShift = (t &>> 16) | (t &>> 12)
            let divided = orShift / (p2 &+ 1)
            // ~t is bitwise NOT; C evaluates `~t >> N` as `(~t) >> N`.
            let notT = ~t
            let inner = divided & 215 & (notT &>> p1Shift)
            let notInner = ~inner
            let sq = t &* t
            let mul = (p0 &+ 1) &* sq &* notInner
            return mul / (p3 &+ 1)
        }
        let l = f(t0, 8 &+ p1 / 2)
        let r = f(t1, 8 &- p1 / 2)
        return (UInt8(truncatingIfNeeded: l),
                UInt8(truncatingIfNeeded: r))
    }

    /// Song 7 (`bytebeat_songs.inc:234`).
    /// `s = t * ((t>>(14-p1/7) | t>>(9-p0/11)) & (92-p3) & t>>(5+p2/10))`
    @inlinable
    static func song7(t0: Int32, t1: Int32, p0: Int32, p1: Int32, p2: Int32, p3: Int32) -> (UInt8, UInt8) {
        @inline(__always) func f(_ t: Int32) -> Int32 {
            let a = 14 &- p1 / 7
            let b = 9 &- p0 / 11
            let c = 5 &+ p2 / 10
            let inner = ((t &>> a) | (t &>> b)) & (92 &- p3) & (t &>> c)
            return t &* inner
        }
        return (UInt8(truncatingIfNeeded: f(t0)),
                UInt8(truncatingIfNeeded: f(t1)))
    }
}
